vikan_wash_homepage:
    pattern:  /
    defaults: { _controller: VikanWashBundle:Default:index }

vikan_wash_laundryplace:
    pattern:  /laundryplace/{slug}
    defaults: { _controller: VikanWashBundle:Laundry:show }

